Cinemas/Cinemas/Models/Login.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinemas.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Login
    {
        public int ID { get; set; }
        public int CustomerId { get; set; }

        [Display(Name = "Login ID")]
        [Required(ErrorMessage = "Login ID is Required")]
        public string loginId { get; set; }

        [Display(Name = "Password")]
        [Required(ErrorMessage = "Password is Required")]
        public string password { get; set; }
        public int IsAdmin { get; set; }

        public virtual Customer Customer { get; set; }
    }
}

Cinemas/Cinemas/Controllers/LoginsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Cinemas.Models;

namespace Cinemas.Controllers
{
    public class LoginsController : Controller
    {
        private LuxeCinemasEntities db = new LuxeCinemasEntities();

        // GET: Logins
        public ActionResult Index()
        {
            try
            {
                //var logins = db.Logins.Include(l => l.Customer);
                //return View(logins.ToList());
                return View();
            }
            catch (Exception ex)
            {
                return View("~/Views/Shared/Error.cshtml");
            }
        }

        // GET: Logins/Details/5
        public ActionResult Details()
        {
            try
            {
                var logins = db.Logins.Include(l => l.Customer);
                return View(logins.ToList());
            }
            catch (Exception ex)
            {
                return View("~/Views/Shared/Error.cshtml");
            }
        }

        // GET: Logins/Create
        public ActionResult Create()
        {
            try
            {
                ViewBag.CustomerId = new SelectList(db.Customers, "ID", "firstName");
                return View();
            }
            catch (Exception ex)
            {
                return View("~/Views/Shared/Error.cshtml");
            }
        }


        // POST: Logins/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,CustomerId,loginId,password,IsAdmin")] Login login)
        {
            try
            {


                if (ModelState.IsValid)
                {
                    db.Logins.Add(login);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                ViewBag.CustomerId = new SelectList(db.Customers, "ID", "firstName", login.CustomerId);
                return View(login);
            }
            catch (Exception ex)
            {
                return View("~/Views/Shared/Error.cshtml");
            }
        }



        [HttpPost]
        public ActionResult Validate(Login login)
        {
            try
            {
                //var result = db1.Logins.Where(cls => cls.loginId.Equals(login.ID) && cls.password.Equals(login.password)).Any();
                string loginName = login.loginId;
                string pwd = login.password;
                var record = db.Logins.Where(u => u.loginId == loginName && u.password == pwd).FirstOrDefault();

                if (record != null && !string.IsNullOrEmpty(Convert.ToString(record.CustomerId)))
                {
                    Session["CustId"] = Convert.ToString(record.CustomerId);
                    return RedirectToAction("Create", "Bookings");

                }
                else
                {
                    return View("~/Views/Shared/LoginFailed.cshtml");
                }
            }


            catch (Exception ex)
            {
                return View("~/Views/Shared/Error.cshtml");
            }


        }


        // GET: Logins/Edit/5
        public ActionResult Edit(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Login login = db.Logins.Find(id);
                if (login == null)
                {
                    return HttpNotFound();
                }
                ViewBag.CustomerId = new SelectList(db.Customers, "ID", "firstName", login.CustomerId);
                return View(login);
            }
            catch (Exception ex)
            {
                return View("~/Views/Shared/Error.cshtml");
            }
        }

        // POST: Logins/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,CustomerId,loginId,password,IsAdmin")] Login login)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(login).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ViewBag.CustomerId = new SelectList(db.Customers, "ID", "firstName", login.CustomerId);
                return View(login);
            }

            catch (Exception ex)
            {
                return View("~/Views/Shared/Error.cshtml");
            }
        }

        // GET: Logins/Delete/5
        public ActionResult Delete(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Login login = db.Logins.Find(id);
                if (login == null)
                {
                    return HttpNotFound();
                }
                return View(login);
            }
            catch (Exception ex)
            {
                return View("~/Views/Shared/Error.cshtml");
            }
        }

        // POST: Logins/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Login login = db.Logins.Find(id);
                db.Logins.Remove(login);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View("~/Views/Shared/Error.cshtml");
            }
        }

        protected override void Dispose(bool disposing)
        {

            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);


        }
    }
}

Cinemas/Cinemas/Views/Logins/Create.cshtml
@model Cinemas.Models.Login

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Login</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CustomerId, "CustomerId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CustomerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.loginId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.loginId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.loginId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsAdmin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsAdmin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IsAdmin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Cinemas/Cinemas/Views/Logins/Delete.cshtml
@model Cinemas.Models.Login

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Login</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.loginId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.loginId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsAdmin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsAdmin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer.firstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.firstName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Cinemas/Cinemas/Views/Logins/Details.cshtml
@*@model Cinemas.Models.Login

    @{
        ViewBag.Title = "Details";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }

    <h2>Details</h2>

    <div>
        <h4>Login</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.loginId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.loginId)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.password)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.password)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.IsAdmin)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.IsAdmin)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Customer.firstName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Customer.firstName)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
        @Html.ActionLink("Back to List", "Index")
    </p>*@


@model IEnumerable<Cinemas.Models.Login>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Login Information</h2>

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.loginId)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.password)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsAdmin)
            </th>*@
        <th>
            @Html.DisplayNameFor(model => model.Customer.firstName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.loginId)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.password)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsAdmin)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Customer.firstName)
            </td>
            @*<td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>*@
        </tr>
    }

</table>

Cinemas/Cinemas/Views/Logins/Edit.cshtml
@model Cinemas.Models.Login

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Login</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        @Html.HiddenFor(model => model.CustomerId)

        <div class="form-group">
            @Html.LabelFor(model => model.loginId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.loginId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.loginId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsAdmin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsAdmin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IsAdmin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Cinemas/Cinemas/Views/Logins/Index.cshtml
@model Cinemas.Models.Login
@{
    ViewBag.Title = "Validate";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<h2>Validate</h2>*@
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
</head>
<body>
    @using (Html.BeginForm("Validate","Logins"))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Customer Login</h4>
            <hr />


            <div class="form-group">
                @Html.LabelFor(model => model.loginId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.loginId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.loginId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.PasswordFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @*@Html.Label("New User", htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-10">
                    @Html.ActionLink("Sign up", "Create", "Customers", new { area = "" }, new { htmlAttributes = new { @class = "form-control" } })
                </div>

            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Login" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</body>
</html>

Cinemas/Cinemas/Views/Logins/Validate.cshtml
@model Cinemas.Models.Login
@{
    ViewBag.Title = "Validate";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Validate</h2>
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Customer</h4>
            <hr />


            <div class="form-group">
                @Html.LabelFor(model => model.loginId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.loginId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.loginId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.PasswordFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @*@Html.Label("New User", htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-10">
                    @Html.ActionLink("Sign up", "Create", "Customers", new { area = "" }, new { htmlAttributes = new { @class = "form-control" } })
                </div>

            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Login" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</body>
</html>